# Generated by Django 6.0.4 on 2026-08-23 15:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0002_alter_question_options_choice_is_correct_choice_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OBSERVATION', 'General Observation'), ('ACADEMIC', 'Academic Scaffolding'), ('WELLBEING', 'Wellbeing & Stress Support'), ('INTERVENTION', 'Targeted Intervention'), ('AI_STRATEGY', 'AI Pedagogical Plan')], default='OBSERVATION', help_text='Note classification', max_length=20)),
                ('content', models.TextField(help_text='Private educator observation, conference log, or intervention notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(help_text='The student this note pertains to', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_notes', to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(blank=True, help_text='Optional assessment submission linked to this observation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_notes', to='assessments.submission')),
                ('teacher', models.ForeignKey(help_text='The educator who recorded the note', on_delete=django.db.models.deletion.CASCADE, related_name='authored_teacher_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Teacher Observation Note',
                'verbose_name_plural': 'Teacher Observation Notes',
                'ordering': ['-created_at'],
            },
        ),
    ]
