# Generated by Django 6.0.4 on 2026-08-23 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('SCHOOL', 'Schooling (10th / 12th)'), ('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)')], help_text='Target qualification tier (School, UG, PG)', max_length=10)),
                ('category', models.CharField(choices=[('VARK', 'Learning Style (VARK)'), ('MINDSET', 'Growth Mindset & Resilience'), ('STRESS', 'Stress & Pressure Response'), ('COMM', 'Communication & Feedback')], default='VARK', help_text='Psychometric category', max_length=10)),
                ('prompt', models.TextField(help_text='The question or scenario presented to the student')),
                ('subtitle', models.CharField(blank=True, help_text='Short subtitle or contextual hint', max_length=255)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which the question appears in the quiz')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this question is active in quizzes')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'ordering': ['tier', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text presented to the student', max_length=300)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Order of display among choices')),
                ('visual_weight', models.PositiveSmallIntegerField(default=0, help_text='Visual learning affinity weight (0-5)')),
                ('auditory_weight', models.PositiveSmallIntegerField(default=0, help_text='Auditory learning affinity weight (0-5)')),
                ('kinesthetic_weight', models.PositiveSmallIntegerField(default=0, help_text='Kinesthetic/hands-on learning affinity weight (0-5)')),
                ('growth_weight', models.PositiveSmallIntegerField(default=0, help_text='Growth mindset & resilience affinity weight (0-5)')),
                ('stress_weight', models.PositiveSmallIntegerField(default=0, help_text='Stress vulnerability weight (0-5)')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='assessments.question')),
            ],
            options={
                'verbose_name': 'Choice',
                'verbose_name_plural': 'Choices',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('SCHOOL', 'Schooling (10th / 12th)'), ('UG', 'Undergraduate (UG)'), ('PG', 'Postgraduate (PG)')], help_text='Academic tier at the time of submission', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('visual_score', models.IntegerField(default=0, help_text='Visual affinity percentage')),
                ('auditory_score', models.IntegerField(default=0, help_text='Auditory affinity percentage')),
                ('kinesthetic_score', models.IntegerField(default=0, help_text='Kinesthetic affinity percentage')),
                ('growth_score', models.IntegerField(default=0, help_text='Growth mindset score percentage')),
                ('stress_score', models.IntegerField(default=0, help_text='Stress response score percentage')),
                ('persona_title', models.CharField(default='Evolving Learner', max_length=120)),
                ('persona_tagline', models.CharField(default='Developing multi-modal study instincts.', max_length=255)),
                ('persona_summary', models.TextField(blank=True)),
                ('teacher_motivation', models.TextField(blank=True, help_text='How to motivate and assign tasks to this student')),
                ('teacher_communication', models.TextField(blank=True, help_text='Best feedback and communication channels')),
                ('teacher_caution', models.TextField(blank=True, help_text='Stress triggers and what to watch out for')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Assessment Submission',
                'verbose_name_plural': 'Assessment Submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.question')),
                ('selected_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.choice')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.submission')),
            ],
            options={
                'verbose_name': 'Submission Answer',
                'verbose_name_plural': 'Submission Answers',
                'unique_together': {('submission', 'question')},
            },
        ),
    ]
