# Generated by Django 6.0.4 on 2026-08-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['tier', 'section', 'order', 'id'], 'verbose_name': 'Question', 'verbose_name_plural': 'Questions'},
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False, help_text='Whether this is the correct answer (for cognitive/subject tests)'),
        ),
        migrations.AddField(
            model_name='choice',
            name='tag',
            field=models.CharField(blank=True, help_text='Associated trait or style tag (e.g. Achiever, STEM/Analytical, Leadership-leaning)', max_length=60),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard'), ('GENERAL', 'General / Survey')], default='GENERAL', help_text='Question difficulty level', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.CharField(choices=[('PART_1', 'Part 1: Core Adaptive Screening Test'), ('PART_2', 'Part 2: Whole-Student Profile (Shared)')], default='PART_1', help_text='Part 1 (Adaptive Test) or Part 2 (Whole-Student Profile)', max_length=15),
        ),
        migrations.AddField(
            model_name='submission',
            name='cognitive_score',
            field=models.IntegerField(default=0, help_text='Cognitive/knowledge accuracy percentage'),
        ),
        migrations.AddField(
            model_name='submission',
            name='interests_tag',
            field=models.CharField(blank=True, help_text='STEM / Creative / People / Business', max_length=60),
        ),
        migrations.AddField(
            model_name='submission',
            name='open_message_to_teacher',
            field=models.TextField(blank=True, help_text='Student open message to teacher'),
        ),
        migrations.AddField(
            model_name='submission',
            name='personality_tag',
            field=models.CharField(blank=True, help_text='Achiever / Explorer / Collaborator / Analyst', max_length=60),
        ),
        migrations.AddField(
            model_name='submission',
            name='soft_skills_summary',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='submission',
            name='wellbeing_flag',
            field=models.CharField(default='Green', help_text='Green / Amber / Red', max_length=20),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(help_text='Option text presented to the student', max_length=350),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('READING', 'Subject Knowledge — Reading Comprehension'), ('AWARENESS', 'Subject Knowledge — General Awareness'), ('PATTERN', 'Cognitive Aptitude — Pattern & Code Reasoning'), ('LOGIC', 'Cognitive Aptitude — Verbal / Logical Reasoning'), ('VARK', 'Learning Style Probes'), ('PERSONALITY', 'Personality (Achiever / Explorer / Collaborator / Analyst)'), ('INTERESTS', 'Interests & Career Inclination'), ('WELLBEING', 'Wellbeing & Motivation'), ('SOFTSKILLS', 'Soft Skills & Behavior')], default='VARK', help_text='Psychometric or assessment category', max_length=20),
        ),
    ]
